version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=security_admin
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 9001:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25
  adminer:
    container_name: adminer
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 9080:8080

